#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

sketchybar --trigger system_wake


##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=40 blur_radius=30 color=0x40000000

sketchybar --bar height=40        \
                 blur_radius=30   \
                 position=top     \
                 sticky=off       \
                 padding_left=10  \
                 padding_right=10 \
                 color=$BAR_COLOR

sketchybar --default icon.font="SF Pro:Semibold:15.0"  \
                     icon.color=$BAR_COLOR                \
                     label.font="SF Pro:Semibold:15.0" \
                     label.color=$ACCENT_COLOR                \
                     background.color=$ITEM_BG_COLOR       \
                     background.corner_radius=5            \
                     background.height=24                  \
                     padding_left=5                    \
                     padding_right=5                   \
                     label.padding_left=4              \
                     label.padding_right=4             \
                     icon.padding_left=4               \
                     icon.padding_right=4

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"



  # -- Left Side Items --
source $ITEM_DIR/canvas.sh # Canvas app
source $ITEM_DIR/docs.sh # Docs app
source $ITEM_DIR/gpt.sh # GPT app
source $ITEM_DIR/mail.sh # Mail app
source $ITEM_DIR/messages.sh # Messages app 
source $ITEM_DIR/paramount.sh # Paramount app
source $ITEM_DIR/youtube.sh # Youtube app
source $ITEM_DIR/max.sh # Max app




# -- Right Side Of Notch Items --
source $ITEM_DIR/media.sh


# --- Right Side Items ---
source $ITEM_DIR/calendar.sh # Calendar app
source $ITEM_DIR/volume.sh # Volume app
source $ITEM_DIR/battery.sh # Time remaining app
#source $ITEM_DIR/battery.sh # Battery app



##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
